name: CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup sbt and JDK
        uses: olafurpg/setup-scala@v13
        with:
          java-version: 11
          sbt-version: 1.9.0

      - name: Cache sbt and Ivy2 directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Publish to GitHub Package Registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sbt -Dpublish.credentials="GitHub Package Registry:${GITHUB_USERNAME}:maven.pkg.github.com:${GITHUB_USERNAME}:${GITHUB_TOKEN}" publish
