name: CI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: sbt

      - name: Cache sbt and Ivy2 directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Setup sbt launcher
        run: |
          curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.deb
          sudo dpkg -i sbt.deb || sudo apt-get install -f -y
          sbt sbtVersion

      - name: Publish to GitHub Package Registry
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          sbt -Dpublish.credentials="GitHub Package Registry:${GITHUB_USERNAME}:maven.pkg.github.com:${GITHUB_USERNAME}:${GITHUB_TOKEN}" publish
