name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # sesuaikan versi kamu

      - name: Setup sbt
        run: |
          curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.0/sbt-1.9.0.deb
          sudo dpkg -i sbt.deb
          sbt sbtVersion

      - name: Build with sbt
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # inject token ke environment variable
        run: sbt compile
