name: Scala Package Publish

on:
  push:
    branches:
      - main  # atau branch lainnya yang kamu gunakan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17' # Sesuaikan dengan versi yang kamu butuhkan

    - name: Install sbt
      uses: coursier/setup-action@v1
      with:
        apps: sbt

    - name: Run tests and publish
      run: sbt publish
